"""
This file is autogenerated and should not be modified manually.
Any changes made to this file may be overwritten.
"""

from gfx.pedal import GfxPedal


class VolumePedal(GfxPedal):
    @classmethod
    @property
    def output(self):
        return self.knobs["Output"]

    @classmethod
    @property
    def on_off(self):
        return self.switches["On/Off"]

