"""
This file is autogenerated and should not be modified manually.
Any changes made to this file may be overwritten.
"""

from pyfx.config import PedalConfig
from pyfx.pedal import PyFxPedal


class Pedal1PedalBase(PyFxPedal):
    """Pedal 1 Class"""

    def __init__(self, pedal_config: PedalConfig):
        super().__init__(pedal_config)

