"""
This file is autogenerated and should not be modified manually.
Any changes made to this file may be overwritten.
"""

from gfx.pedal import GfxPedal


class SaturatePedal(GfxPedal):
    @classmethod
    @property
    def amount(self):
        return self.knobs["Amount"]

    @classmethod
    @property
    def on_off(self):
        return self.switches["On/Off"]

